### ISSUE TITLE
[feature request] Expose the "EPSG Geodetic Parameter Dataset" version

### ISSUE THREAD

**Issue by jmckenna** [OSGeo/spatialreference.org#21]
- the former epsg.io includes in the footer `Powered by EPSG database 11.001` which is very useful to the user
- the current spatialreference.org footer states `Built on 2024-04-04 using PROJ 9.4.0`
  - could the footer be updated magically to something like `Built on 2024-04-04 using PROJ 9.4.0, EPSG v11.004` ?

**Comment by jjimenezshaw** [comment]
"magically"? :P
What I get from pyproj is in a file like this one: https://crs-explorer.proj.org/metadata.txt
There is more information than just the version of EPSG

Do you think there is a better location to put all that information?

Something like "Built on 2024-04-04 using [PROJ](https://proj.org/) 9.4.0, [Detailed versions here](https://crs-explorer.proj.org/metadata.txt)"?

```
pyproj info:
    pyproj: 3.6.1
      PROJ: 9.4.0
  data dir: /usr/share/proj/
user_data_dir: /tmp/proj
PROJ DATA (recommended version): 1.17
PROJ Database: 1.3
EPSG Database: v11.004 [2024-02-24]
ESRI Database: ArcGIS Pro 3.2 [2023-11-02]
IGNF Database: 3.1.0 [2019-05-24]

System:
    python: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
executable: /home/venv/bin/python3
   machine: Linux-6.5.0-1015-azure-x86_64-with-glibc2.35

Python deps:
   certifi: 2024.2.2
    Cython: None
setuptools: 59.6.0
       pip: 24.0
```

**Comment by rouault** [comment]
@jjimenezshaw You can extract the information field by field with https://pyproj4.github.io/pyproj/stable/api/database.html#pyproj-database-get-database-metadata

**Comment by jmckenna** [comment]
How about: 

"Built on 2024-04-04 using [PROJ](https://proj.org/) 9.4.0 (see [here](https://crs-explorer.proj.org/metadata.txt) for detailed versions)"

**Comment by jjimenezshaw** [comment]
I can extract the information of EPSG version, sure. My point is that there are more DBs, like esri. Should we say only one version? Or give all the information?

**Comment by jmckenna** [comment]
@jjimenezshaw I prefer less development work ha.  So I propose:


"Built on 2024-04-04 using [PROJ](https://proj.org/) 9.4.0 (for detailed versions see [here](https://crs-explorer.proj.org/metadata.txt))"
