### ISSUE TITLE
improve SEO

### ISSUE THREAD

**Issue by jmckenna** [OSGeo/spatialreference.org#24]
- try googling a sample EPSG code, such as "epsg 3978"
- notice that the spatialreference.org [associated page](https://spatialreference.org/ref/epsg/3978/) is not highly ranked (if at all)
- view-source of that page, and you'll see missing [meta tags](https://developers.google.com/search/docs/crawling-indexing/special-tags) for `description`, `keywords` etc (that help search engines crawl the pages)
- other tips for discovery (this is nothing new) include managing your site in the [Google Search Console](https://search.google.com/search-console/welcome), setting up a sitemap for your site, etc.

Maybe try adding a description tag first?

For comparison, view-source of https://epsg.io/3978

**Comment by jjimenezshaw** [comment]
Hi @jmckenna 
I know that unfortunately we are not very high in the rank. To be honest, I am surprised that in 2024 search engines are making any difference if there is data in the `description` tag that is already in the content of the page. It would be basically duplicating the text. The main information is already in the `title` tag (code and name)!

About the sitemap, https://github.com/OSGeo/spatialreference.org/pull/17 is there since March 

If you let me be evil, I understand that epsg dot io is better ranked: it has a lot of adds from Google. We have none. That makes our page less interesting to be visited for the adds provider... that is also the search engine. But maybe I am too suspicious.

**Comment by jmckenna** [comment]
Hi @jjimenezshaw I've found that even in 2024, doing the basics still helps.  For example, I notice that we lack a [robots.txt](https://spatialreference.org/robots.txt), for machines to crawl. (see [how-to](https://developers.google.com/search/docs/crawling-indexing/robots/create-robots-txt))

I'm also ok to close this ticket now, someday someone can come back to tackle, and re-open.

**Comment by jjimenezshaw** [comment]
I will add a non restrictive robots.txt (2 lines) and the `description` and `keywords` tags... just repeating the information that is already there.
Probably it is more effective that other pages link to ours... but I have no control over that ;)

**Comment by neteler** [comment]
This tool is giving some insights:
https://seorch.net --> URL: https://spatialreference.org/

Besides many good SEO test results there are also some issues listed. Summary:

- No Meta Description found. 
- The <title> Tag is too short: 25 characters.
- The <title> Tag has too few words: 3.
- The website text is too short: 54 words. Text length should be more than 400 words. 
- Links without TITLE attribute: 15
- No `<h1>` Tags found. (Missing heading)
- No robots.txt found.

**Comment by jjimenezshaw** [comment]
Thanks @neteler that is giving some useful tips.
I run it in a specific CRS, and it gives slightly different (but similar) results. I think what we want to be reached per CRS, that is what people search.

What make me nuts is the "The <title> Tag has too few words: 3." Really? Look at the title of a Google page ;)

**Comment by neteler** [comment]
> What make me nuts is the "The <title> Tag has too few words: 3." Really? Look at the title of a Google page ;)

Seorch is not my system, I was just the messenger :-)

**Comment by jmckenna** [comment]
thanks @jjimenezshaw, worth a try!

**Comment by neteler** [comment]
I have made an attempt to add an intro in #26.

Still, pages like https://spatialreference.org/ref/epsg/3978/ are looking pretty nerdy to me.
For people coming directly to this page, it may not be obvious what this is all about :-)

So, what about adding some text between

`EPSG:3978`

and

`NAD83 / Canada Atlas Lambert`

?

**Comment by neteler** [comment]
Update: trying the search from above again:
https://www.google.com/search?q=epsg+3978

Now (at least here in Germany) this site ranks 3rd, so the situation slowly  seems to improve.

**Comment by jmckenna** [comment]
Agreed, improving (2nd result here).
