### ISSUE TITLE
Re-add information for deprecated refs

### ISSUE THREAD

**Issue by mwtoews** [OSGeo/spatialreference.org#3]
Thanks all for the much needed updates to sr.org!

This is a minor regression from the old sr.org website. For instance with CRS EPSG:28473, compare old and new pages.

The old version https://web.archive.org/web/20210617073835/https://spatialreference.org/ref/epsg/pulkovo-1942-gauss-kruger-13n/

> Deprecated: Change of CRS name to indicate longitude of origin. Use [EPSG:2503](https://spatialreference.org/ref/epsg/2503/) instead.

The new version https://spatialreference.org/ref/epsg/28473/ only has a short message:

> Deprecated!

But is missing other potentially useful information. The only workaround is to navigate to the linked official source https://epsg.org/crs_28473/Pulkovo-1942-Gauss-Kruger-13N.html to find the replacement and reason.

Also `projinfo -k crs EPSG:28473` shows the alternative non-deprecated CRS.

**Comment by rouault** [comment]
@mwtoews As the scripts used pyproj4, and from what I can see the proj_get_non_deprecated() function is non mapped to pyproj, we can't provide the link to the non-deprecated CRS (the reason itself is not currently imported in the PROJ database, but that's a very minor point).  @snowman Do you think proj_get_non_deprecated() could be mapped to pyproj ?
