### ISSUE TITLE
include the PROJECTION name?

### ISSUE THREAD

**Issue by mdsumner** [OSGeo/spatialreference.org#31]
feature request, I'd love to see the projection name (when it exists). I always go for the WKT1 page to find out i.e. "Lambert_Conformal_Conic_2S", it's always the key bit of information I want, i.e. *why was this crs chosen ... what is the family*.  Sadly this seems to be the last bit of information anyone shares, but if we could search for code and see it on the page that would improve my life immensely :)

  (Even quicker is the proj4 string name, but I can't see any problem with this longer name). 

https://spatialreference.org/ref/epsg/6492/wkt.html

Perhaps when there's no PROJECTION, it could list "GEOGCS"?  I'm not across how many other cases there might be.

**Comment by jjimenezshaw** [comment]
@mdsumner the projection is already there:
`Projection method name: Lambert Conic Conformal (2SP)`
https://spatialreference.org/ref/epsg/6492/
Is that what you want?

**Comment by mdsumner** [comment]
oh goodness. very sorry, will train myself to see it!
